### ISSUE TITLE
What is   0: ""  in Prefs.yml?

### ISSUE THREAD

**Issue by markkrueg** [Tethered/FactionsPro#45]
Testing v1.4 BETA, there are these two strange lines in generated Prefs.yml 

```
--
MaxFactionNameLength: 20
MaxPlayersPerFaction: 10
ClaimingEnabled: true
OnlyLeadersAndOfficersCanInvite: true
OfficersCanClaim: true
PlotSize: 25
Member:
  claim: false
  demote: false
  home: true
  invite: false
  kick: false
  motd: false
  promote: false
  sethome: false
  unclaim: false
  unsethome: false
  0: ""
Officer:
  claim: true
  demote: false
  home: true
  invite: true
  kick: true
  motd: true
  promote: false
  sethome: true
  unclaim: true
  unsethome: true
  0: ""
...
```
