### ISSUE TITLE
Version is incorrect in plugin.yml

### ISSUE THREAD

**Issue by markkrueg** [Tethered/FactionsPro#46]
Testing v1.4 BETA

Still says 1.3.3, should be 1.4

```
name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.3
main: FactionsPro\FactionMain
api: [1.12.0]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
```
